version: 2
jobs:
  build_and_push:
    docker:
      - image: docker:17.05.0-ce-git

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup Env
          command: |
            echo 'export IMAGE_TAG=${CIRCLE_TAG:-latest}' >> $BASH_ENV
            echo 'export IMAGE_NAME=image' >> $BASH_ENV
      - run:
          name: Build and push Docker image
          command: |
            source $BASH_ENV
            docker build -t martyns0n/$IMAGE_NAME:$IMAGE_TAG .
            docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
            docker push martyns0n/$IMAGE_NAME:$IMAGE_TAG
workflows:
  version: 2
  # for master brunch
  deploy-dev:
    jobs:
      - build_and_push:
          filters:
            branches:
              only:
                - master